/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BestTradeGUI;

import static BestTradeGUI.UIManager.*;

/**
 *
 * @author User
 */
public class TradeScreen extends javax.swing.JPanel {

    /**
     * Creates new form TradeScreen
     */
    public TradeScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchForProductButton = new javax.swing.JButton();
        viewMyProfileButton = new javax.swing.JButton();

        searchForProductButton.setText("Search For Product");
        searchForProductButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchForProductButtonMouseClicked(evt);
            }
        });

        viewMyProfileButton.setText("View My Profile");
        viewMyProfileButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewMyProfileButtonMouseClicked(evt);
            }
        });
        viewMyProfileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewMyProfileButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(searchForProductButton, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(119, 119, 119)
                .addComponent(viewMyProfileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(viewMyProfileButton, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                    .addComponent(searchForProductButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(154, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void viewMyProfileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewMyProfileButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewMyProfileButtonActionPerformed

    private void searchForProductButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchForProductButtonMouseClicked
        // TODO add your handling code here:
        frame.getContentPane().removeAll();
        frame.getContentPane().add(searchItemScreen);
        setVisible(false);
        searchItemScreen.setVisible(true);
    }//GEN-LAST:event_searchForProductButtonMouseClicked

    private void viewMyProfileButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewMyProfileButtonMouseClicked
        // TODO add your handling code here:
        frame.getContentPane().removeAll();
        frame.getContentPane().add(myProfilePanel);
        setVisible(false);
        myProfilePanel.setVisible(true);
    }//GEN-LAST:event_viewMyProfileButtonMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton searchForProductButton;
    public javax.swing.JButton viewMyProfileButton;
    // End of variables declaration//GEN-END:variables
}
