/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BestTradeGUI;

import static BestTradeGUI.LoginPanel.client;
import static BestTradeGUI.LoginPanel.items;
import static BestTradeGUI.UIManager.*;
import Database.Database;
import java.io.IOException;
import static java.lang.Integer.parseInt;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;



/**
 *
 * @author User
 */
public class ActivationCodeScreen extends javax.swing.JPanel {
    
    Database database;
    /**
     * Creates new form ActivationCodeScreen
     */
    public ActivationCodeScreen(Database database) {
        initComponents();
        this.database = database;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        codeArea = new javax.swing.JTextField();
        codeLabel = new javax.swing.JLabel();
        okButton = new javax.swing.JButton();
        backBut = new javax.swing.JButton();

        codeArea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                codeAreaKeyTyped(evt);
            }
        });

        codeLabel.setText("Please enter the Activation Code");

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        backBut.setText("BACK");
        backBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addComponent(okButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(codeLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(codeArea, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(backBut, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(163, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(backBut, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(codeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(codeArea, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(okButton)
                .addContainerGap(174, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        // TODO add your handling code here:
        
        int activCode = parseInt(codeArea.getText());
        
        if(activCode == database.getActivationCode()){
            
            database.addClient();
            try {
                database.refresh();
            } catch (IOException ex) {
                Logger.getLogger(ActivationCodeScreen.class.getName()).log(Level.SEVERE, null, ex);
            }
            //database.client = database.justClient;
            TradeScreen TradeScreen = new TradeScreen(database);
            UIManager.frame.add(TradeScreen);
            setVisible(false);
            TradeScreen.setVisible(true);
        }
        else{
            
            JOptionPane.showMessageDialog(null, "Activation Code is wrong", "Warning" , JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_okButtonActionPerformed

    private void codeAreaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codeAreaKeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_codeAreaKeyTyped

    private void backButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButActionPerformed
        // TODO add your handling code here:
        LoginPanel loginPanel = new LoginPanel();
        UIManager.frame.add(loginPanel);
        setVisible(false);
        loginPanel.setVisible(true);
        
    }//GEN-LAST:event_backButActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBut;
    public javax.swing.JTextField codeArea;
    public javax.swing.JLabel codeLabel;
    public javax.swing.JButton okButton;
    // End of variables declaration//GEN-END:variables
}