/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BestTradeGUI;

import static BestTradeGUI.UIManager.*;
import Database.Database;
import ModelClasses.*;
import java.util.ArrayList;
import javax.swing.JLabel;

/**
 *
 * @author ezgicakir
 */
public class MyProductsPanel extends javax.swing.JPanel {
    JLabel[] labels;
    int countClick, labelNo,itemSize, whichLabel;
    ArrayList<Item> itemList;
    Database database;
    
   
    /**
     * Creates new form MyProductsPanel
     */
    public MyProductsPanel(Database db) {
        database = db;
        initComponents();
        
        
        whichLabel = 0;
        labelNo =7;
        labels = new JLabel[labelNo];
        labels[0] = jLabel1;
        labels[1] = jLabel2;
        labels[2] = jLabel3;
        labels[3] = jLabel4;
        labels[4] = jLabel5;
        labels[5] = jLabel6;
        labels[6] = jLabel7;
        
        
        itemList = db.itemsList;
        if(db.client  != null){
            itemList = db.client.getItems();
            System.out.println("NULLL MIII      LAANNN");
        }
        
        itemSize = itemList.size();
        System.out.println("ASDKASKDASID   " + itemSize + "   ASdSDADSADASD");
        countClick =0;
        
        int i =0;
        while(i < labelNo){
            if(i < itemSize)
                labels[i].setText(itemList.get(i).getTitle());
            
            else
                labels[i].setVisible(false);
            i++;    
        }
        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        previousButton = new javax.swing.JButton();
        nextButton = new javax.swing.JButton();

        jLabel1.setText("jLabel1");
        jLabel1.setPreferredSize(new java.awt.Dimension(300, 20));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel2.setText("jLabel2");
        jLabel2.setPreferredSize(new java.awt.Dimension(300, 20));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel3.setText("jLabel3");
        jLabel3.setPreferredSize(new java.awt.Dimension(300, 20));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jLabel4.setText("jLabel4");
        jLabel4.setPreferredSize(new java.awt.Dimension(300, 20));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        jLabel5.setText("jLabel5");
        jLabel5.setPreferredSize(new java.awt.Dimension(300, 20));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        jLabel6.setText("jLabel6");
        jLabel6.setPreferredSize(new java.awt.Dimension(300, 20));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        jLabel7.setText("jLabel7");
        jLabel7.setPreferredSize(new java.awt.Dimension(300, 20));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        backButton.setText("BACK");
        backButton.setPreferredSize(new java.awt.Dimension(85, 35));
        backButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backButtonMouseClicked(evt);
            }
        });

        previousButton.setText("previous");
        previousButton.setToolTipText("");
        previousButton.setPreferredSize(new java.awt.Dimension(80, 29));
        previousButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousButtonActionPerformed(evt);
            }
        });

        nextButton.setText("next");
        nextButton.setPreferredSize(new java.awt.Dimension(80, 29));
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(95, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(previousButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nextButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(previousButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nextButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        // TODO add your handling code here:
        countClick++;
        
        //System.out.println("count: " + countClick);
        int i = countClick*labelNo;
        int lastPage = itemSize/labelNo;
        if(countClick > lastPage  && itemSize % labelNo != 0){
            int k = (lastPage)*labelNo;
            for(int j =0 ; j < labelNo; j++){
        
                if(j < itemSize)
                    labels[j].setText(itemList.get(k).getTitle());
            
                else
                    labels[j].setVisible(false);
                k++;    
            }
        }
        else if(countClick > itemSize/labelNo +1 && itemSize % labelNo == 0){
            int k = (lastPage-1)*labelNo;
            for(int j =0 ; j < labelNo; j++){
        
                if(j < itemSize)
                    labels[j].setText(itemList.get(k).getTitle());
            
                else
                    labels[j].setVisible(false);
                k++;    
            }
        }
        else {
            if(countClick >= 0){
                for(int j =0 ; j < labelNo; j++){
        
                    if(i < itemSize)
                        labels[j].setText(itemList.get(i).getTitle());
            
                    else
                        labels[j].setVisible(false);
                    i++;    
                }
            
            }
            else{
                i =0;
                for(int j =0 ; j < labelNo; j++){
        
                    if(i < itemSize)
                        labels[j].setText(itemList.get(i).getTitle());
            
                    else
                        labels[j].setVisible(false);
                    i++;    
                }
            }
            
       }
    }//GEN-LAST:event_nextButtonActionPerformed

    private void previousButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousButtonActionPerformed
        // TODO add your handling code here:
        countClick--;
        int i = countClick*labelNo;
        //System.out.println("count: " + countClick);
        int lastPage = itemSize/labelNo;
        if(countClick > lastPage  && itemSize % labelNo != 0){
            int k = (lastPage)*labelNo;
            for(int j =0 ; j < labelNo; j++){
        
                if(j < itemSize)
                    labels[j].setText(itemList.get(k).getTitle());
            
                else
                    labels[j].setVisible(false);
                k++;    
            }
        }
        else if(countClick > itemSize/labelNo +1 && itemSize % labelNo == 0){
            int k = (lastPage-1)*labelNo;
            for(int j =0 ; j < labelNo; j++){
        
                if(j < itemSize)
                    labels[j].setText(itemList.get(k).getTitle());
            
                else
                    labels[j].setVisible(false);
                k++;    
            }
        }
        else {
            if(countClick >= 0){
                for(int j =0 ; j < labelNo; j++){
        
                    if(i < itemSize)
                        labels[j].setText(itemList.get(i).getTitle());
            
                    else
                        labels[j].setVisible(false);
                    i++;    
                }
            
            }
            else{
                i =0;
                for(int j =0 ; j < labelNo; j++){
        
                    if(i < itemSize)
                        labels[j].setText(itemList.get(i).getTitle());
            
                    else
                        labels[j].setVisible(false);
                    i++;    
                }
            }
            
       }
        
    }//GEN-LAST:event_previousButtonActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        whichLabel = 1;
        EditItemPanel editItemPanel = new EditItemPanel(database, whichLabel, countClick);
        UIManager.frame.add(editItemPanel);
        setVisible(false);
        editItemPanel.setVisible(true);
        
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        whichLabel = 2;
        EditItemPanel editItemPanel = new EditItemPanel(database,whichLabel, countClick);
        UIManager.frame.add(editItemPanel);
        setVisible(false);
        editItemPanel.setVisible(true);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:  
        whichLabel = 3;
        EditItemPanel editItemPanel = new EditItemPanel(database,whichLabel, countClick);
        UIManager.frame.add(editItemPanel);
        setVisible(false);
        editItemPanel.setVisible(true);
        
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        whichLabel = 4;
        EditItemPanel editItemPanel = new EditItemPanel(database,whichLabel, countClick);
        UIManager.frame.add(editItemPanel);
        setVisible(false);
        editItemPanel.setVisible(true);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        whichLabel = 5;
        EditItemPanel editItemPanel = new EditItemPanel(database,whichLabel, countClick);
        UIManager.frame.add(editItemPanel);
        setVisible(false);
        editItemPanel.setVisible(true);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        whichLabel = 6;
        EditItemPanel editItemPanel = new EditItemPanel(database,whichLabel, countClick);
        UIManager.frame.add(editItemPanel);
        setVisible(false);
        editItemPanel.setVisible(true);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        whichLabel = 7;
        EditItemPanel editItemPanel = new EditItemPanel(database,whichLabel, countClick);
        UIManager.frame.add(editItemPanel);
        setVisible(false);
        editItemPanel.setVisible(true);
    }//GEN-LAST:event_jLabel7MouseClicked

    private void backButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backButtonMouseClicked
        // TODO add your handling code here:
        //frame.getContentPane().removeAll();
        //frame.getContentPane().add(myProfilePanel);
        MyProfilePanel myProfilePanel = new MyProfilePanel(database);
        UIManager.frame.add(myProfilePanel);
        setVisible(false);
        myProfilePanel.setVisible(true);
    }//GEN-LAST:event_backButtonMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton nextButton;
    private javax.swing.JButton previousButton;
    // End of variables declaration//GEN-END:variables
}
