/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BestTradeGUI;

import static BestTradeGUI.LoginPanel.client;
import static BestTradeGUI.UIManager.*;
import Database.Database;
import ModelClasses.*;

/**
 *
 * @author berkt
 */
public class MyProfilePanel extends javax.swing.JPanel {
    //Client theclient;
    Database database;
    /**
     * Creates new form MyProfilePanel
     */
    public MyProfilePanel(Database database) {
        this.database = database;
        initComponents();
        
        if(database.client != null){
            //theclient = database.client;
            
            nameLabel.setText(database.client.getName() + " " +database.client.getSurname());
            uniLabel.setText(database.client.getUniversity());
            mailLabel.setText(database.client.getEmail());
            usernameLabel.setText(database.client.getUserName());
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameLabel = new javax.swing.JLabel();
        uniLabel = new javax.swing.JLabel();
        mailLabel = new javax.swing.JLabel();
        editProfile = new javax.swing.JButton();
        messagesBut = new javax.swing.JButton();
        backBut = new javax.swing.JButton();
        itemsButton = new javax.swing.JButton();
        usernameLabel = new javax.swing.JLabel();

        nameLabel.setText("Name Surname");

        uniLabel.setText("University Name");

        mailLabel.setText("E-mail");

        editProfile.setText("Edit Profile");
        editProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editProfileMouseClicked(evt);
            }
        });

        messagesBut.setText("Messages");
        messagesBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                messagesButMouseClicked(evt);
            }
        });

        backBut.setText("BACK");
        backBut.setToolTipText("");
        backBut.setMaximumSize(new java.awt.Dimension(85, 35));
        backBut.setMinimumSize(new java.awt.Dimension(85, 35));
        backBut.setPreferredSize(new java.awt.Dimension(85, 35));
        backBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backButMouseClicked(evt);
            }
        });

        itemsButton.setText("Sold Products");
        itemsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemsButtonMouseClicked(evt);
            }
        });

        usernameLabel.setText("Username");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backBut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(messagesBut, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69)
                        .addComponent(itemsButton))
                    .addComponent(mailLabel)
                    .addComponent(uniLabel)
                    .addComponent(nameLabel)
                    .addComponent(usernameLabel)
                    .addComponent(editProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(129, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(backBut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(usernameLabel)
                .addGap(18, 18, 18)
                .addComponent(nameLabel)
                .addGap(18, 18, 18)
                .addComponent(uniLabel)
                .addGap(18, 18, 18)
                .addComponent(mailLabel)
                .addGap(18, 18, 18)
                .addComponent(editProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(itemsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(messagesBut, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void editProfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editProfileMouseClicked
        // TODO add your handling code here:
        EditProfilePanel editProfilePanel = new EditProfilePanel(database);
        UIManager.frame.add(editProfilePanel);
        setVisible(false);
        editProfilePanel.setVisible(true);
    }//GEN-LAST:event_editProfileMouseClicked

    private void backButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backButMouseClicked
        // TODO add your handling code here:
        TradeScreen tradeScreen = new TradeScreen(database);
        UIManager.frame.add(tradeScreen);
        setVisible(false);
        tradeScreen.setVisible(true);
        
    }//GEN-LAST:event_backButMouseClicked

    private void messagesButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_messagesButMouseClicked
        // TODO add your handling code here:
        //MESSAGES WILL BE DISPLAYED ON ANOTHER FRAME
        MessageScreen messageScreen = new MessageScreen(database);
        UIManager.frame.add(messageScreen);
        setVisible(false);
        messageScreen.setVisible(true);
    }//GEN-LAST:event_messagesButMouseClicked

    private void itemsButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemsButtonMouseClicked
        // TODO add your handling code here:
        //frame.getContentPane().removeAll();
        //frame.getContentPane().add(myProductsPanel);
        MyProductsPanel myProductsPanel = new MyProductsPanel(database);
        UIManager.frame.add(myProductsPanel);
        setVisible(false);
        myProductsPanel.setVisible(true);
        
    }//GEN-LAST:event_itemsButtonMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBut;
    public javax.swing.JButton editProfile;
    private javax.swing.JButton itemsButton;
    public javax.swing.JLabel mailLabel;
    public javax.swing.JButton messagesBut;
    public javax.swing.JLabel nameLabel;
    public javax.swing.JLabel uniLabel;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables
}
