/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BestTradeGUI;


import static BestTradeGUI.UIManager.frame;
import BestTradeGUI.*;
import static BestTradeGUI.UIManager.*;
import java.awt.Component;
import java.awt.Dimension;
import java.util.ArrayList;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.border.EmptyBorder;
import static BestTradeGUI.UIManager.frame;
import Database.Database;
import ModelClasses.Client;
import ModelClasses.Item;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import static BestTradeGUI.UIManager.*;
import ModelClasses.Item;
import java.awt.Image;
import java.io.IOException;
import javax.swing.AbstractButton;
import javax.swing.JLabel;

/**
 *
 * @author User
 */

public class SearchItemScreen extends javax.swing.JPanel {

    /**
     * Creates new form SearchItemScreen
     */
    
    private Database database;
    private String price;
    private String categoryName;
    private String typeName;
    public String print="Hie";
    private boolean categorySelected;
    private boolean typeSelected;
    private boolean priceSelected;
    Item item;
    int countClick, whichLabel,itemNo, selectedItemSize;
    String type;
    ArrayList<Item> selectedItemList = new ArrayList<Item>();
    ArrayList<JButton> buttonsArr = new ArrayList<JButton>();
    ArrayList<JLabel> labelArr = new ArrayList<JLabel>();
    ArrayList<JLabel> labelPriceArr = new ArrayList<JLabel>();
    

    public SearchItemScreen(Database database) throws IOException {
         
        this.database=database;
         categorySelected=false;
         typeSelected=false;
         priceSelected=false;
         countClick=0;
         whichLabel=0;
         itemNo = 8;
         database.refresh();
         database.getItem(categoryName,price,typeName,categorySelected,typeSelected,priceSelected);
         selectedItemList = database.getArr();
         selectedItemSize = selectedItemList.size();
         System.out.println("constructor size: " + selectedItemSize);
         initComponents();
         
         
        buttonsArr.add(Button1);
        buttonsArr.add(Button2);
        buttonsArr.add(button3);
        buttonsArr.add(button4);
        buttonsArr.add(button5);
        buttonsArr.add(button6);
        buttonsArr.add(button7);
        buttonsArr.add(button8);
        labelArr.add(label1);
        labelArr.add(label2);
        labelArr.add(label3);
        labelArr.add(label4);
        labelArr.add(label5);
        labelArr.add(label6);
        labelArr.add(label7);
        labelArr.add(label8);
        labelPriceArr.add(price1);
        labelPriceArr.add(price2);
        labelPriceArr.add(price3);
        labelPriceArr.add(price4);
        labelPriceArr.add(price5);
        labelPriceArr.add(price6);
        labelPriceArr.add(price7);
        labelPriceArr.add(price8);
        printItems(countClick);
        
        item = database.getArr().get(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        optionsPanel = new javax.swing.JPanel();
        priceLabel = new javax.swing.JLabel();
        typeLabel = new javax.swing.JLabel();
        filtersLabel = new javax.swing.JLabel();
        categoryLabel = new javax.swing.JLabel();
        priceRange = new javax.swing.JComboBox<>();
        categoryComboBox = new javax.swing.JComboBox<>();
        typeComboBox = new javax.swing.JComboBox<>();
        apply = new javax.swing.JButton();
        abovePanel = new javax.swing.JPanel();
        searchField = new javax.swing.JTextField();
        viewMyProfileButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        searchButton = new javax.swing.JButton();
        searchF2 = new javax.swing.JTextField();
        itemPanel = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        label5 = new javax.swing.JLabel();
        label7 = new javax.swing.JLabel();
        label6 = new javax.swing.JLabel();
        label8 = new javax.swing.JLabel();
        price5 = new javax.swing.JLabel();
        price6 = new javax.swing.JLabel();
        price7 = new javax.swing.JLabel();
        price8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        button4 = new javax.swing.JButton();
        Button2 = new javax.swing.JButton();
        button3 = new javax.swing.JButton();
        Button1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        label3 = new javax.swing.JLabel();
        label4 = new javax.swing.JLabel();
        label1 = new javax.swing.JLabel();
        label2 = new javax.swing.JLabel();
        price1 = new javax.swing.JLabel();
        price2 = new javax.swing.JLabel();
        price3 = new javax.swing.JLabel();
        price4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        button6 = new javax.swing.JButton();
        button5 = new javax.swing.JButton();
        button7 = new javax.swing.JButton();
        button8 = new javax.swing.JButton();
        prevpageButton = new javax.swing.JButton();
        nextpageButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();

        priceLabel.setText("Price");

        typeLabel.setText("Type");

        filtersLabel.setText("Filters");

        categoryLabel.setText("Category");

        priceRange.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0-100", "100-200", "200-300", "300-..." }));
        priceRange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceRangeActionPerformed(evt);
            }
        });

        categoryComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Book", "Electronics", "Furniture", "Others", "Musics", "Notes" }));
        categoryComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryComboBoxActionPerformed(evt);
            }
        });

        typeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Zero", "Second Hand" }));
        typeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeComboBoxActionPerformed(evt);
            }
        });

        apply.setText("Apply");
        apply.setPreferredSize(new java.awt.Dimension(50, 30));
        apply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout optionsPanelLayout = new javax.swing.GroupLayout(optionsPanel);
        optionsPanel.setLayout(optionsPanelLayout);
        optionsPanelLayout.setHorizontalGroup(
            optionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optionsPanelLayout.createSequentialGroup()
                .addGroup(optionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(optionsPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(filtersLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(optionsPanelLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(optionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(priceRange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(priceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(optionsPanelLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(optionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(typeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(typeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(apply, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 30, Short.MAX_VALUE))
            .addGroup(optionsPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(optionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(categoryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(categoryLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        optionsPanelLayout.setVerticalGroup(
            optionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optionsPanelLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(filtersLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(categoryLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(categoryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99)
                .addComponent(priceLabel)
                .addGap(6, 6, 6)
                .addComponent(priceRange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(typeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(typeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(apply, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        searchField.setText("search");
        searchField.setMaximumSize(null);
        searchField.setPreferredSize(new java.awt.Dimension(0, 0));
        searchField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchFieldMouseClicked(evt);
            }
        });

        viewMyProfileButton.setText("View My Profile");
        viewMyProfileButton.setPreferredSize(new java.awt.Dimension(139, 35));
        viewMyProfileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewMyProfileButtonActionPerformed(evt);
            }
        });

        backButton.setText("BACK");
        backButton.setPreferredSize(new java.awt.Dimension(80, 35));
        backButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backButtonMouseClicked(evt);
            }
        });

        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        searchF2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchF2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout abovePanelLayout = new javax.swing.GroupLayout(abovePanel);
        abovePanel.setLayout(abovePanelLayout);
        abovePanelLayout.setHorizontalGroup(
            abovePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abovePanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(abovePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(abovePanelLayout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(abovePanelLayout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(searchF2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34)
                .addComponent(searchButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 143, Short.MAX_VALUE)
                .addComponent(viewMyProfileButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );
        abovePanelLayout.setVerticalGroup(
            abovePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abovePanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, abovePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(abovePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewMyProfileButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchButton)
                    .addComponent(searchF2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        label5.setText("jLabel9");
        label5.setMaximumSize(new java.awt.Dimension(100, 25));
        label5.setMinimumSize(new java.awt.Dimension(100, 25));
        label5.setPreferredSize(new java.awt.Dimension(100, 25));

        label7.setText("jLabel11");
        label7.setMaximumSize(new java.awt.Dimension(100, 25));
        label7.setMinimumSize(new java.awt.Dimension(100, 25));
        label7.setPreferredSize(new java.awt.Dimension(100, 25));

        label6.setText("jLabel10");
        label6.setMaximumSize(new java.awt.Dimension(100, 25));
        label6.setMinimumSize(new java.awt.Dimension(100, 25));
        label6.setPreferredSize(new java.awt.Dimension(100, 25));

        label8.setText("jLabel12");
        label8.setMaximumSize(new java.awt.Dimension(100, 25));
        label8.setMinimumSize(new java.awt.Dimension(100, 25));
        label8.setPreferredSize(new java.awt.Dimension(100, 25));

        price5.setText("jLabel1");

        price6.setText("jLabel1");

        price7.setText("jLabel1");

        price8.setText("jLabel1");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(label5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(price5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(35, 35, 35)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(label6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(price6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(38, 38, 38)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(label7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(price7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(label8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(price8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(39, 39, 39))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(price5)
                    .addComponent(price6)
                    .addComponent(price7)
                    .addComponent(price8))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        button4.setText("jButton4");
        button4.setMaximumSize(new java.awt.Dimension(110, 110));
        button4.setMinimumSize(new java.awt.Dimension(110, 110));
        button4.setPreferredSize(new java.awt.Dimension(110, 110));
        button4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button4MouseClicked(evt);
            }
        });

        Button2.setText("jButton2");
        Button2.setMaximumSize(new java.awt.Dimension(110, 110));
        Button2.setMinimumSize(new java.awt.Dimension(110, 110));
        Button2.setPreferredSize(new java.awt.Dimension(110, 110));
        Button2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button2MouseClicked(evt);
            }
        });

        button3.setText("jButton3");
        button3.setMaximumSize(new java.awt.Dimension(110, 110));
        button3.setMinimumSize(new java.awt.Dimension(110, 110));
        button3.setPreferredSize(new java.awt.Dimension(110, 110));
        button3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button3MouseClicked(evt);
            }
        });

        Button1.setText("jButton1");
        Button1.setMaximumSize(new java.awt.Dimension(110, 110));
        Button1.setMinimumSize(new java.awt.Dimension(110, 110));
        Button1.setPreferredSize(new java.awt.Dimension(110, 110));
        Button1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button1MouseClicked(evt);
            }
        });
        Button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(Button2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(button3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(button4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 22, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        label3.setText("jLabel7");
        label3.setMaximumSize(new java.awt.Dimension(100, 25));
        label3.setMinimumSize(new java.awt.Dimension(100, 25));
        label3.setPreferredSize(new java.awt.Dimension(100, 25));

        label4.setText("jLabel8");
        label4.setMaximumSize(new java.awt.Dimension(100, 25));
        label4.setMinimumSize(new java.awt.Dimension(100, 25));
        label4.setPreferredSize(new java.awt.Dimension(100, 25));

        label1.setText("jLabel1");
        label1.setMaximumSize(new java.awt.Dimension(100, 25));
        label1.setMinimumSize(new java.awt.Dimension(100, 25));
        label1.setPreferredSize(new java.awt.Dimension(100, 25));

        label2.setText("jLabel6");
        label2.setMaximumSize(new java.awt.Dimension(100, 25));
        label2.setMinimumSize(new java.awt.Dimension(100, 25));
        label2.setPreferredSize(new java.awt.Dimension(100, 25));

        price1.setText("jLabel1");

        price2.setText("jLabel1");

        price3.setText("jLabel1");

        price4.setText("jLabel1");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(label1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(price1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(46, 46, 46)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(label2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(price2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(45, 45, 45)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(label3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(price3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(label4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(price4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(price1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(price2)
                    .addComponent(price3)
                    .addComponent(price4))
                .addGap(0, 0, 0))
        );

        button6.setText("jButton6");
        button6.setMaximumSize(new java.awt.Dimension(110, 110));
        button6.setMinimumSize(new java.awt.Dimension(110, 110));
        button6.setPreferredSize(new java.awt.Dimension(110, 110));
        button6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button6MouseClicked(evt);
            }
        });

        button5.setText("jButton5");
        button5.setMaximumSize(new java.awt.Dimension(110, 110));
        button5.setMinimumSize(new java.awt.Dimension(110, 110));
        button5.setPreferredSize(new java.awt.Dimension(110, 110));
        button5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button5MouseClicked(evt);
            }
        });

        button7.setText("jButton7");
        button7.setPreferredSize(new java.awt.Dimension(110, 110));
        button7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button7MouseClicked(evt);
            }
        });

        button8.setText("jButton8");
        button8.setPreferredSize(new java.awt.Dimension(110, 110));
        button8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button8MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(button5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(button6, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(button7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(button8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(button5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(button6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(button7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(button8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout itemPanelLayout = new javax.swing.GroupLayout(itemPanel);
        itemPanel.setLayout(itemPanelLayout);
        itemPanelLayout.setHorizontalGroup(
            itemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(itemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(itemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        itemPanelLayout.setVerticalGroup(
            itemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        prevpageButton.setText("previous");
        prevpageButton.setPreferredSize(new java.awt.Dimension(50, 30));
        prevpageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prevpageButtonActionPerformed(evt);
            }
        });

        nextpageButton.setText("next");
        nextpageButton.setPreferredSize(new java.awt.Dimension(80, 30));
        nextpageButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nextpageButtonMouseClicked(evt);
            }
        });

        clearButton.setText("Clear Filters");
        clearButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(abovePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(optionsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(clearButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(itemPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(prevpageButton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nextpageButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(abovePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(itemPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nextpageButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(prevpageButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(optionsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clearButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void viewMyProfileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewMyProfileButtonActionPerformed
        // TODO add your handling code here:
       MyProfilePanel myProfilePanel = new MyProfilePanel(database);
        UIManager.frame.add(myProfilePanel);
        setVisible(false);
        myProfilePanel.setVisible(true);  
    }//GEN-LAST:event_viewMyProfileButtonActionPerformed

    
    private void priceRangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceRangeActionPerformed
        // TODO add your handling code here:
        Object selectedItem = priceRange.getSelectedItem();
        price = selectedItem.toString();
        priceSelected=true;
    }//GEN-LAST:event_priceRangeActionPerformed

    private void backButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backButtonMouseClicked
        // TODO add your handling code here: 
        TradeScreen tradeScreen = new TradeScreen(database);
        UIManager.frame.add(tradeScreen);
        setVisible(false);
        tradeScreen.setVisible(true);     
    }//GEN-LAST:event_backButtonMouseClicked

    private void button8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button8MouseClicked
        // TODO add your handling code here:
        whichLabel = 8;
        int index = countClick*itemNo + whichLabel-1;
        item = selectedItemList.get(index);
        
        ViewItemScreen viewItemScreen = new ViewItemScreen(database,item);
        UIManager.frame.add(viewItemScreen);
        setVisible(false);
        viewItemScreen.setVisible(true);   
        
    }//GEN-LAST:event_button8MouseClicked

    private void button7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button7MouseClicked
        // TODO add your handling code here:
        whichLabel = 7;
        int index = countClick*itemNo + whichLabel-1;
        item = selectedItemList.get(index);
        ViewItemScreen viewItemScreen = new ViewItemScreen(database,item);
        UIManager.frame.add(viewItemScreen);
        setVisible(false);
        viewItemScreen.setVisible(true); 
    }//GEN-LAST:event_button7MouseClicked

    private void button6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button6MouseClicked
        // TODO add your handling code here:
        whichLabel = 6;
        int index = countClick*itemNo + whichLabel-1;
        item = selectedItemList.get(index);
        ViewItemScreen viewItemScreen = new ViewItemScreen(database,item);
        UIManager.frame.add(viewItemScreen);
        setVisible(false);
        viewItemScreen.setVisible(true); 
    }//GEN-LAST:event_button6MouseClicked

    private void button5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button5MouseClicked
        // TODO add your handling code here:
        whichLabel = 5;
        int index = countClick*itemNo + whichLabel-1;
        item = selectedItemList.get(index);
        ViewItemScreen viewItemScreen = new ViewItemScreen(database,item);
        UIManager.frame.add(viewItemScreen);
        setVisible(false);
        viewItemScreen.setVisible(true); 
    }//GEN-LAST:event_button5MouseClicked

    private void button4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button4MouseClicked
        // TODO add your handling code here:
        whichLabel = 4;
        int index = countClick*itemNo + whichLabel-1;
        item = selectedItemList.get(index);
        ViewItemScreen viewItemScreen = new ViewItemScreen(database,item);
        UIManager.frame.add(viewItemScreen);
        setVisible(false);
        viewItemScreen.setVisible(true); 
    }//GEN-LAST:event_button4MouseClicked

    private void button3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button3MouseClicked
        // TODO add your handling code here:
        whichLabel = 3;
        int index = countClick*itemNo + whichLabel-1;
        item = selectedItemList.get(index);
        ViewItemScreen viewItemScreen = new ViewItemScreen(database,item);
        UIManager.frame.add(viewItemScreen);
        setVisible(false);
        viewItemScreen.setVisible(true); 
    }//GEN-LAST:event_button3MouseClicked

    private void Button2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button2MouseClicked
        // TODO add your handling code here:
        whichLabel = 2;
        int index = countClick*itemNo + whichLabel-1;
        item = selectedItemList.get(index);
        ViewItemScreen viewItemScreen = new ViewItemScreen(database,item);
        UIManager.frame.add(viewItemScreen);
        setVisible(false);
        viewItemScreen.setVisible(true); 
    }//GEN-LAST:event_Button2MouseClicked

    private void Button1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button1MouseClicked
        // TODO add your handling code here:
        whichLabel = 1;
        int index = countClick*itemNo + whichLabel-1;
        item = selectedItemList.get(index);
        ViewItemScreen viewItemScreen = new ViewItemScreen(database,item);
        UIManager.frame.add(viewItemScreen);
        setVisible(false);
        viewItemScreen.setVisible(true); 
    }//GEN-LAST:event_Button1MouseClicked

    private void prevpageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prevpageButtonActionPerformed
        // TODO add your handling code here:
        countClick--;
        printItems(countClick);
    }//GEN-LAST:event_prevpageButtonActionPerformed

    private void Button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button1ActionPerformed
        // TODO add your handling code here:
        //database.getArr().get(1).toString();  
        ShowDetailedItem showDetailedItem = new ShowDetailedItem(this);
        UIManager.frame.add(showDetailedItem);

        setVisible(false);
        showDetailedItem.setVisible(true);  
    }//GEN-LAST:event_Button1ActionPerformed

    private void applyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applyActionPerformed
        // TODO add your handling code here:

        database.getItem(categoryName,price,typeName,categorySelected,typeSelected,priceSelected);
        selectedItemList = database.getArr();
        selectedItemSize = selectedItemList.size();
        
        if(selectedItemList.size() > 0)
        print =database.PrintItem(0);
        
        printItems(countClick);
    }//GEN-LAST:event_applyActionPerformed

    private void categoryComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryComboBoxActionPerformed
        // TODO add your handling code here:
         
        Object selectedItem = categoryComboBox.getSelectedItem();
    
        categoryName = selectedItem.toString();
        categorySelected=true;
      
    }//GEN-LAST:event_categoryComboBoxActionPerformed

    private void typeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeComboBoxActionPerformed
        // TODO add your handling code here:
        Object selectedItem = typeComboBox.getSelectedItem();
    
        typeName = selectedItem.toString();
        typeSelected=true;
    }//GEN-LAST:event_typeComboBoxActionPerformed

    private void clearButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearButtonMouseClicked
        // TODO add your handling code here:
        categoryComboBox.setSelectedIndex(0);
        priceRange.setSelectedIndex(0);
        typeComboBox.setSelectedIndex(0);
        categorySelected=false;
        typeSelected = false;
        priceSelected=false;
        database.getItem(categoryName,price,typeName,categorySelected,typeSelected,priceSelected);
        selectedItemList = database.getArr();
        selectedItemSize = selectedItemList.size();
        countClick =0;
        searchF2.setText("");
        printItems(countClick);
    }//GEN-LAST:event_clearButtonMouseClicked
    
    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:
        String keyword = searchF2.getText();
        database.searchItem(keyword);
        selectedItemList = database.getSearchArr();
        selectedItemSize = selectedItemList.size();
        if(database.getSearchArr().size() > 0)
        {
            print =database.PrintSearch(0);
        }
        printItems(countClick);
    
    }//GEN-LAST:event_searchButtonActionPerformed

    private void nextpageButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextpageButtonMouseClicked
        // TODO add your handling code here:
        countClick++;
        printItems(countClick);
    }//GEN-LAST:event_nextpageButtonMouseClicked

    private void searchFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchFieldMouseClicked
        // TODO add your handling code here:
        searchField.setText(""); 
    }//GEN-LAST:event_searchFieldMouseClicked

    private void searchF2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchF2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchF2ActionPerformed

    void printItems(int clickCount){
        int lastpage = selectedItemSize / itemNo;
        
        if((clickCount > lastpage  && selectedItemSize % itemNo != 0))
            clickCount = lastpage;
        if( clickCount >= selectedItemSize/itemNo && selectedItemSize % itemNo == 0)
            clickCount = lastpage-1;
        if(clickCount < 0)
            clickCount = 0;
        System.out.println("lastpage : " + lastpage + "selectedsize: " + selectedItemSize + "countclick: " + clickCount);
        countClick = clickCount;
        int i = clickCount*itemNo;

        for(int j =0 ; j < itemNo; j++){
        
            if(i < selectedItemSize){
                labelArr.get(j).setText(selectedItemList.get(i).getTitle());
                labelPriceArr.get(j).setText(selectedItemList.get(i).getPrice()+"");
                buttonsArr.get(j).setIcon(selectedItemList.get(i).getPhoto());
                
                labelArr.get(j).setVisible(true);
                labelPriceArr.get(j).setVisible(true);
                buttonsArr.get(j).setVisible(true);
            }
            else{
                labelArr.get(j).setVisible(false);
                labelPriceArr.get(j).setVisible(false);
                buttonsArr.get(j).setVisible(false);
            }
            i++;    
        }
   
       
    }
    public Database getDatabase()
    {
        return database;
    }
    
    public boolean getTypeSelected()
    {
        return typeSelected;
    }
    
    public boolean getCategorySelected()
    {
        return categorySelected;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button1;
    private javax.swing.JButton Button2;
    private javax.swing.JPanel abovePanel;
    private javax.swing.JButton apply;
    public javax.swing.JButton backButton;
    private javax.swing.JButton button3;
    private javax.swing.JButton button4;
    private javax.swing.JButton button5;
    private javax.swing.JButton button6;
    private javax.swing.JButton button7;
    private javax.swing.JButton button8;
    private javax.swing.JComboBox<String> categoryComboBox;
    private javax.swing.JLabel categoryLabel;
    private javax.swing.JButton clearButton;
    private javax.swing.JLabel filtersLabel;
    private javax.swing.JPanel itemPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label3;
    private javax.swing.JLabel label4;
    private javax.swing.JLabel label5;
    private javax.swing.JLabel label6;
    private javax.swing.JLabel label7;
    private javax.swing.JLabel label8;
    private javax.swing.JButton nextpageButton;
    private javax.swing.JPanel optionsPanel;
    private javax.swing.JButton prevpageButton;
    private javax.swing.JLabel price1;
    private javax.swing.JLabel price2;
    private javax.swing.JLabel price3;
    private javax.swing.JLabel price4;
    private javax.swing.JLabel price5;
    private javax.swing.JLabel price6;
    private javax.swing.JLabel price7;
    private javax.swing.JLabel price8;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JComboBox<String> priceRange;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField searchF2;
    private javax.swing.JTextField searchField;
    private javax.swing.JComboBox<String> typeComboBox;
    private javax.swing.JLabel typeLabel;
    private javax.swing.JButton viewMyProfileButton;
    // End of variables declaration//GEN-END:variables
}